cc_library(
  name = "process_state",
  srcs = ["process_state.h",
          "process_state.cc"],
  deps = ["//chime/core/framework:device_types",
          "//chime/core/memory:allocator_lib",
          "//chime/core/platform:mutex",
          "//chime/core/platform:thread_annotations",
          "//chime/core/util:optional",
          "//chime/core/platform:strcat"]
)